# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BqEuqh7Huhd1-lVAnJ3ehXuhN22ubIMh
"""

#This project adds and searches contacts using a dictuonary.
 #contacts = {}
#print("Contact dictionary is ready.")

# Empty dictionary for contacts
#contacts = {}

#print("=====CONTACT BOOK=====")

#While True
    #print("/n1. Add Contact")
    #print("2. Search Contact")
    #print("3. Exit")

    #choice = input("Enter your choice:") .strip(1)

    #if choice =="1":
       #name = input("ali:") .strips () . title()
       #phone = input("03001234567:") .strips()
       #email = input("ali@gmail.com:").strips()

       #if name == "" or phone =="" or email== "":
           #print("All information is required.")
      #else:
           #contacts[ali] = {
               #"phone": 03001234567,
               #"email": ali@gmail.com
               #}
               #print("Contact added successfully.")
       #elif choice =="2"
            #search_name = input(
                #"Enter contact name to search: "
            #). strips() . title()

            #if search_name in contacts:
                #print("/nContact founf!")
                #print("Name:", ali)
                #print("phone:",contacts[search_name]["phone"])
                #print("Email:". contacts[search_name]["email"])
            #else:
                #print("Contact not found")


           #elif choice =="3":
                  #print("Contacts Book closed.")
                  #break

           #else:
                 #print("Invalid choice. Enter 1, 2, or 3.")

